# Site
repository: samirshrestha/samirshrestha.github.io
# favicon: images/favicon.ico

# Personal info
name: Samir Shrestha
title: Senior Android Application Developer
email: g.samirshrestha@gmail.com
website: http://samirshrestha.github.io/

# Social links
# twitter_username: facespics
github_username:  samirshrestha
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: i.samirshrestha
linkedin_username: samir-shrestha-74491398
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Samir and I'm a senior android application developer. I have worked at a number of companies gaining teamwork and leadership skills.
 

  I am most skilled in: <mark>Android</mark> and <mark>Sleeping</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in app development some of my other interests and hobbies are:
   - Bike touring
   - Following sports

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
